Announcement
zjutjh/boomerang pull request #9
Opened 2018-07-26 06:02 UTC by SilverBullete

2018-07-27 11:10 UTC, cccRaim requested changes

2018-07-27 11:10 UTC, cccRaim commented on app/Http/Controllers/AnnouncementController.php
> +        $message = Announcement::where('id',4)->first();
id=4？

2018-07-27 11:10 UTC, cccRaim commented on app/Http/Controllers/AnnouncementController.php
> +            $summary = substr($content,0,20);
简介应该可以自定义，而不是仅仅截取内容的前二十个字

2018-07-27 11:10 UTC, cccRaim commented on database/migrations/2018_07_23_000000_create_announcement_table.php
>              $table->tinyInteger('status')->default(0)->comment('状态, 是否显示，0为显示，1为显示');
`0为显示，1为显示`？

2018-07-27 11:10 UTC, cccRaim commented on app/Http/Controllers/AnnouncementController.php
>              ->get();
你这样获取的是数组，不符合你给出的数据文档

2018-07-27 11:10 UTC, cccRaim commented on app/Http/Controllers/AnnouncementController.php
> +            ['title' => $title, 'content' => $content, 'summary' => $summary, 'status' => 0]
假如status的0表示不可用，那么这次插入的公告就是不可用？

2018-07-27 12:12 UTC, cccRaim requested changes

2018-07-27 12:12 UTC, cccRaim commented on database/migrations/2018_07_23_000000_create_announcement_table.php
> +            $table->tinyInteger('status')->default(0)->comment('状态, 是否显示，0为显示，1为不显示');
按照1为true，0为false的逻辑，应该是0为不显示，1为显示

2018-07-27 12:12 UTC, cccRaim commented on app/Http/Controllers/Auth/LoginController.php
> +        $openid = $request->get('openid');//请求得到用户openid
autoLogin应该是接受code，而不是接口openid

2018-07-27 12:24 UTC, cccRaim approved these changes

2018-07-30 04:22 UTC, zzhutianyu commented
ok

2018-07-30 04:23 UTC, merged